# Site settings
title: The Classical Language Toolkit
#email: kyle@kyle-p-johnson.com
description: > # this means to ignore newlines until "baseurl:"
  NLP for pre-modern languages
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cltk.org" # the base hostname & protocol for your site
#twitter_username: kyle_p_johnson
github_username: cltk
github_cltk: cltk/cltk
copyright: Ⓒ 2021 Kyle P. Johnson
lang: en
locale: en_US
logo: /assets/phoenician_aleph.svg
social:
  name: The Classical Language Toolkit
  links:
    - https://github.com/cltk
    - https://docs.cltk.org
author:
  name: CLTK Team
google_site_verification: vKtFmgkyAesRzAAZlNUa2e6O2mcQSkZY-o_kc_Yq0k4

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

timezone: UTC

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
  - .github
